### ISSUE TITLE
Installing a new flutter version completely crashes mac

### ISSUE THREAD

**Issue by patrik-simunic-cz** [fluttertools/sidekick#170]
I've installed the Sidekick app in hopes of having FVM GUI, but something seems to be wrong. I have tried twice to install a flutter version using Sidekick and both times my mac completely crashed - I got a black screen: _"Your computer restarted because of a problem. Press a key or wait a few seconds to continue starting up."_
The first time a tried installing flutter 'stable' second time a tried installing version 2.5.3. Despite crashing both time, the first time flutter version was actually installed, the second version (v2.5.3) was not installed at all.
Interesting thing is, that just FVM alone works perfectly fine - I'm able to install and use any version I like - via CLI.

Versions:
FVM: 2.2.6
Sidekick: 0.2.0
Osx: 11.6.1 (Big Sur)

**Comment by aguilaair** [comment]
Hey @reoretfacio thanks for reporting this! Sorry about the crashes. 

Do you have any logs on what caused the system to crash?

It should look something like: 
![image](https://user-images.githubusercontent.com/29983481/150647366-49f4f5d0-767b-48d6-a22e-98f2f323c0b7.png)


Thanks!

**Comment by aguilaair** [comment]
Alternatively, simply launch the Console app, then in the sidebar, select the System Reports item, and then select the Kernel Panic item (the actual name will include the terms kernel and panic, but it will also have the date and the name of your Mac in the title). 

Source: https://eshop.macsales.com/blog/39112-rocket-yard-guide-understanding-troubleshooting-kernel-panics/

**Comment by reoretfacio** [comment]
@aguilaair No problem, as long as software will exist, bugs will too 😄
Sorry for the delay - I've been waiting until I'll have time to intentionally crash my laptop - which I did 😄
and here is the report from system alter (after restart): https://gist.github.com/reoretfacio/9d81ef917c3fbf4f9ac33f3caf1a1282
_(if you'd like, I can add also more verbose report from Console)_

After looking at the report, I don't think it's a general issue on all macs, but rather some weird combo with some other software (_coreaudiod_?) specifically on my machine. However it's definitely _somehow_ linked to Sidekick, because it crashes exclusively during latest stages of installing a new flutter version.

**Comment by aguilaair** [comment]
Thanks for the report, I'll take a look at it ASAP, don't worry about the delay. 

> as long as software will exist, bugs will too 

Sure, but they should cause a whole system crash 🤣

**Comment by leoafarias** [comment]
@reoretfacio Thanks for the report. Anyway, you can try building the app and running to see if you have the issue, and maybe have better debug logs?

**Comment by reoretfacio** [comment]
@leoafarias I've actually installed Sidekick with installer from latest .dmg release, but as soon as I'll have a few minutes, I'll try to build from source and let you know here 😊

_(Btw. this is purely a hunch, but I have a Boom 3D installed, which is regularly eating up a ton of system resources, so I gather it might be somehow related - idk, maybe it's all together (+ docker, ton of vscode and chrome instances, slack, mysql, mongo, a couple of BE&FE instances, etc.) just a bit too much for my machine. Since I'm actually picking up tomorrow a new M1, I'll also try to replicate the issue on the new killer machine 😄)_

**Comment by leoafarias** [comment]
There has been some process things fixed since last release which we will be deploying soon, I wonder if it has fixed this issue also.

Thanks

**Comment by aguilaair** [comment]
Hey @reoretfacio, would you mind trying this build? It contains the binaries for the latest commit so you don't have to build it from scratch.

[sidekick-macos-dev.dmg.zip](https://github.com/leoafarias/sidekick/files/8164623/sidekick-macos-dev.dmg.1.zip)

**Comment by aguilaair** [comment]
I am closing this issue as it is stale
